### PR TITLE
pick msquic from prerelease/1.5

### PR DESCRIPTION
**Pull request by wfurt**
MsQuic branched prerelease 1.5 and moved main branch to 1.6. As we want to only consume fixesed and not new features we should point and consume the prerelease code. Once runtime branch for RC1, we can branch as well and point main back to main of msquic.

### CODE REVIEW

**Review by safern — APPROVED** [review]
LGTM

**Comment by wfurt** [comment]
https://github.com/microsoft/msquic/blob/main/docs/Release.md#msquic-v16-prerelease

**Comment by nibanks** [comment]
The latest doesn't seem to be pointing to https://github.com/microsoft/msquic/commits/prerelease/1.6's latest commit?

**Comment by wfurt** [comment]
> The latest doesn't seem to be pointing to https://github.com/microsoft/msquic/commits/prerelease/1.6's latest commit?

It seems to point to fdcc086a2ded0eeeb6b78cf473eb2425e2a4ef73. 
https://github.com/microsoft/msquic/commit/fdcc086a2ded0eeeb6b78cf473eb2425e2a4ef73
When I look at it it shows the docs update.

**Comment by nibanks** [comment]
Ah you're right. I just got confused when I clicked on the link and it didn't show the latest commit on top.

**Review by nibanks — APPROVED** [review]

**Comment by wfurt** [comment]
thanks for checking. I do this rarely so it is nice to get extra eyes.

**Comment by wfurt** [comment]
seems to break the official build
```
  -- Configuring incomplete, errors occurred!
    CMake 3.20 or higher is required.  You are running version 3.18.4
```

any thoughts on this @safern and @MattGal ? 
Seems like the base image is different ;(
All checks passed on the PR.

**Comment by wfurt** [comment]
seems like https://github.com/microsoft/msquic/pull/1844
I wish we can do that only when trying to build OpenSSL @nibanks

**Comment by MattGal** [comment]
> any thoughts on this @safern and @MattGal ?

MSQuick builds on hosted VS 2019 machines, which [contain cmake 3.21](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md).  While we keep our VS 2019 machines up to date, we don't currently update beyond what comes with VS, so when moving from hosted windows to buildpool.windows, this is unfortunately expected, although something that will get updated in the future as the base image does.

If there is some compelling reason our images need newer cmake, feel free to create a dotnet/core-eng issue and we'll discuss it in triage.

**Comment by wfurt** [comment]
It seems like it want 3.20 and that should be ok if the machine is the current VS. But it complains that the build machine has only 3.18. It works on the public face but fails on the internal server. I don't even know how to look at what queue it is running on. ;(

**Comment by MattGal** [comment]
> It seems like it want 3.20 and that should be ok if the machine is the current VS. But it complains that the build machine has only 3.18. It works on the public face but fails on the internal server. I don't even know how to look at what queue it is running on. ;(

You can show me arbitrary builds and I'll show you how to check.  It's not obvious, but it's usually there.

**Pull request merged**
