### PR TITLE
Update MsQuic to current main

### PR DESCRIPTION
**Pull request by ManickaP**
MsQuic main https://github.com/microsoft/msquic/commit/8652204d85b4a75fb7a4faf34217a2cb0a001111

### CODE REVIEW

**Comment by wfurt** [comment]
This got broken by https://github.com/microsoft/msquic/pull/3738
Hardcoding toolchain will not work .NET or anybody who needs to cross-compile on their own. 

```
   if ($IsLinux) {
         switch ($Arch) {
             "arm"   {
                 $Arguments += " -DCMAKE_TOOLCHAIN_FILE=""cmake/toolchains/arm-linux.cmake"""
                 $SkipCIBuildCheck = $true
             }
             "arm64" {
                 $Arguments += " -DCMAKE_TOOLCHAIN_FILE=""cmake/toolchains/aarch64-linux.cmake"""
                 $SkipCIBuildCheck = $true
             }
         }
     }
``` 

build should still respect toolchain if it was set - just like it was done before. 

cc: @nibanks @csujedihy

**Comment by csujedihy** [comment]
Being addressed in https://github.com/microsoft/msquic/pull/3828

**Comment by wfurt** [comment]
This still fails because https://github.com/microsoft/msquic/pull/3828 did not bring back the old behavior. .NET does not use specific toolchain files but `--target=aarch64-linux-gnu` to express desired outcome without need to maintain any particular platforms files - cmake can do all that out of the box.    

for me the easiest local "fix" is 
```
furt@ubu18:~/github/dotnet-msquic/src/msquic$ git diff .
diff --git a/scripts/build.ps1 b/scripts/build.ps1
index 1ab1ca786..c0d6ff2e7 100644
--- a/scripts/build.ps1
+++ b/scripts/build.ps1
@@ -403,7 +403,7 @@ function CMake-Generate {
        }
     }
     if ($ToolchainFile -ne "") {
-        $Arguments += " -DCMAKE_TOOLCHAIN_FILE=""$ToolchainFile"""
+#//        $Arguments += " -DCMAKE_TOOLCHAIN_FILE=""$ToolchainFile"""
     }
```

e.g. avoiding the `CMAKE_TOOLCHAIN_FILE` altogether. 

There are different ways how to fix this @csujedihy 
Perhaps best would be keep the `if ($ToolchainFile -eq "")` but pass it in via new argument from for OneBranch builds or wrap all this with `if ($OneBranch)`. That may make it harder for developers to do local cross-builds but I'm not sure if anybody builds the way how current OneBranch build does.   

I'd be happy to test any proposed fix and/or submit PR to msquic. Please let us know.

**Comment by csujedihy** [comment]
@wfurt FYI. I have a PR open https://github.com/microsoft/msquic/pull/3855.

**Review by rzikm — APPROVED** [review]

**Pull request merged**
