### PR TITLE
Update docker tag to the latest one

### PR DESCRIPTION
**Pull request by dkurepa**
Update docker tag to the latest tagging schema

### CODE REVIEW

**Comment by ManickaP** [comment]
CI is not happy about the Linux build:
```
'1.41'
Docker client API version: '1.41'
/usr/bin/docker ps --all --quiet --no-trunc --filter "label=7b4489"
/usr/bin/docker network prune --force --filter "label=7b4489"
/usr/bin/docker pull mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-msquic
Error response from daemon: manifest for mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-msquic not found: manifest unknown: manifest tagged by "ubuntu-18.04-msquic" is not found
##[warning]Docker pull failed with exit code 1, back off 6.637 seconds before retry.
/usr/bin/docker pull mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-msquic
Error response from daemon: manifest for mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-msquic not found: manifest unknown: manifest tagged by "ubuntu-18.04-msquic" is not found
##[warning]Docker pull failed with exit code 1, back off 7.137 seconds before retry.
/usr/bin/docker pull mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-msquic
Error response from daemon: manifest for mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-msquic not found: manifest unknown: manifest tagged by "ubuntu-18.04-msquic" is not found
##[error]Docker pull failed with exit code 1
```

It passed on ARM though...

**Comment by dkurepa** [comment]
Looks like we're missing some dependencies on the image

**Comment by dkurepa** [comment]
I've added powershell to the image, @ManickaP, could you re run the tests please, I don't have the permissions to do so

**Comment by ManickaP** [comment]
I re-ran the pipeline.

**Comment by dkurepa** [comment]
The pipeline is still failing, I *think* we'll have to wait for the release this week. my bad

**Comment by adiaaida** [comment]
@ManickaP I am taking over Djuradj's PR. Can you rerun the pipelines?

**Comment by wfurt** [comment]
Linux build failed with 
```
CMake Error at submodules/CMakeLists.txt:326 (message):
    OpenSSL 1.1.1 not found, found 1.0.2n
```

msquic needs 1.1.1 -> I think it comes from EPEL.

**Comment by wfurt** [comment]
and 1.0 is out of support for very long time.

**Comment by adiaaida** [comment]
Interesting. I wonder why the old images worked if the newer versions have the wrong version of openssl

**Comment by adiaaida** [comment]
I wonder if the difference is that the ubuntu 18.04 image is using the standard ubuntu:18.04 base image vs the msquic image using mcr.microsoft.com/powershell:lts-ubuntu-18.04

**Comment by wfurt** [comment]
I think the package manager should be able to show the source of given package. One easy way would be compare the available sources. If that is same simple update or install should be sufficient IMHO.

**Comment by adiaaida** [comment]
Well this is... weird. I built the container, and did `openssl version` and it says it's 1.1.1

**Comment by wfurt** [comment]
Is there corresponding `-dev` package (for libssl/libcrypto)

**Comment by adiaaida** [comment]
It appears that both libssl/crypto 1.1.1 and libssl/crypto 1.0 are being installed on this image. libssl 1.0 was added to the image 5 years ago. I'm going to check to see if runtime actually still relies on it, and if not, will try to remove that install from the image: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/ubuntu/18.04/amd64/Dockerfile#L79

Given that it's not being installed on any of the other containers, as far as I can tell, I think it is an unnecessary artifact and should be removed.

**Comment by adiaaida** [comment]
Confirmed: that extra line is why this is failing. I've changed it to libssl-dev, and will build runtime to confirm things are ok, but the msquic build will now run successfully

**Comment by adiaaida** [comment]
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/728 and the subsequent rollout to production should unblock this PR.

**Comment by michellemcdaniel** [comment]
@wfurt all testing has passed now!

**Review by wfurt — APPROVED** [review]
nice. Thanks

**Pull request merged**
